server:
  port: 8080

spring:
  config:
    activate:
      on-profile: local

---
spring:
  profile: local
  datasource:
    url: jdbc:postgresql://localhost:5433/products
    username: postgres
    password: 1234
    test-on-borrow: true
    validation-query: SELECT 1 FROM dual
  jpa:
    show-sql: true
    hibernate:
      format-sql: true
      ddl-auto: none

  messages:
    basename: i18n/message
